### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by LamerTex** [marshallthornton/Twitch.tv-Plex-Plugin#5]
I tryed to put the Twitch.tv.bundle directory in /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ 
but in the server (after a reboot) there isn't the new channel, i have to do something else to add the channel in the server? 
Can it work with linux PMS or is not compatible? 
Thanks for the answer :)

**Comment by marshallthornton** [comment]
I don't think it works on Linux because of the flash requirement currently. I don't actually have a Linux installation to test on so I'm not 100% sure on that but I think that flash isn't supported on the Linux version.

I do plan to release a new version soon, I have just been so loaded with work that I have not had time. My schedule should be clearing up in the next month so hopefully after that I can get a new release out that should work on Linux.

**Comment by LamerTex** [comment]
Ok thanks for the answer, if I can help testing the new release on linux somehow I'm avaiable :)

**Comment by RobertARandolph** [comment]
Do you have a working release available? I've been trying to troubleshoot the old version and I can't seem to figure out the "This channel is currently unavailable." error.

**Comment by marshallthornton** [comment]
Can you give it a shot now? zakk4223 made some updates that adjusted how it pulls the video in. I think it still requires flash to work but it should be pulling in the stream page instead of the SWF itself which may or may not fix it. It should at least fix the channel unavailable error and instead throw some kind of flash error if so.

**Comment by ghost** [comment]
I still can't find it among installed Plug-ins in with the new version under linux.
Actually nevermind, I can now watch at least some streams through this plugin.

I think it was an error on my part regarding file ownership and permissions. When I moved the files to the correct folder it got created under my user in the root-group with other permissions than all other plugins, I changed user and group to "plex" with the same permissions as the other files and it worked.

**Comment by marshallthornton** [comment]
So Linux should be good with the latest code, I looked over Zakk's update again and it looks like he removed the Flash requirement as well since it is using the Justin.tv plugin's services to get direct video files.
