### ISSUE TITLE
"crossdomain access denied" error in web app

### ISSUE THREAD

**Issue by dmertl** [marshallthornton/Twitch.tv-Plex-Plugin#9]
When trying to view a stream in the web player I get an error, "Cannot load M3U8: crossdomain access denied" Works fine when using the plex home theater application. I'm guessing this is a browser security problem. Is there any way to fix that?

**Comment by falone** [comment]
I have the same issue.

**Comment by marshallthornton** [comment]
I don't think there is a way to fix this on our end, Plex reads the browser as having Flash capabilities so it directly embeds the player onto the page but the crossdomain.xml sent by Twitch servers allows only Twitch URLs to use the player which is why this error appears. Unless you are able to use localhost to connect to the web interface, Flash is going to block it because of the crossdomain.xml being sent by Twitch.

**Comment by dmertl** [comment]
That's what I figured, thanks for the info.

**Comment by deezit** [comment]
On your modem/router or on your Windows hosts file add something like this to bypass the dns servers :
 plex.newjtv.com YOUR_PLEX_IP

and access plex by this url : http://plex.newjtv.com:32400/web/

Flash will see plex.newjtv.com and the crossdomain will work.
